services:
  frontend:
    build:
      context: ./frontend
    container_name: task-web-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: task-web-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
